language: cpp
compiler: gcc
os:       linux

# Installing additional tools
addons:
  apt:
    packages:
    - lcov
    - rpm

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90; fi
  - g++ -v
  - gcov -v
#  - lcov -v
#  - genhtml -v
#  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build && cmake .. && make VERBOSE=1
  - lcov --zerocounters --directory ./
  - ./mylib/test/btest01 --log_level=all
  - ./mylib/test/gtest01

after_success:
  # use gcov-4.8
#  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
#  - sudo rm /usr/bin/gcov && sudo cp /usr/bin/gcov-4.8 /usr/bin/gcov
#  - gcov -v
  - pwd

  # Preparing Coveralls data by changind data format to a readable one
  - lcov --capture --directory ./ --base-directory ./ --output-file coverage.info
  - ls -alF .

  # ... erasing /usr* and 3rdparty folder data
  - lcov --remove coverage.info "/usr*" "*3rdparty*" -o coverage.info
  - ls -alF .

  - genhtml coverage.info --output-directory coverage.out
  - ls -alF coverage.out

#  - gcov ./mydaemon/test/gtest01.cpp --object-file ./mydaemon/test/CMakeFiles/gtest01.dir/gtest01.cpp.gcno
#  - gcov ./mylib/mymath.cpp --object-file ./mylib/CMakeFiles/MyMath.dir/mymath.cpp.gcno -l
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
#  - coveralls --gcov-options '\-lp' --verbose --dump coveralls.json

  # Sending data to Coveralls
#  - cd $TRAVIS_BUILD_DIR
  - pwd
  - gem install coveralls-lcov
  - coveralls-lcov coverage.info

after_script:
  - pwd
  - ls -alF .
  - ls -alF ./build/mydaemon
  - ls -alF ./build/mylib
  - ls -alF ./build/mylib/test
  - find . -name "*.gc*"
  - cat coverage.info

  - whereis lcov
  - lcov -v
  - wget http://downloads.sourceforge.net/ltp/lcov-1.12-1.noarch.rpm && rpm -U --force lcov-1.12-1.noarch.rpm
  - whereis lcov
  - lcov -v
  - git clone https://github.com/linux-test-project/lcov.git && cd lcov && make install
  - whereis lcov
  - lcov -v

notifications:
  slack: j0ny:tlJolYCjWs5eI2DmeZFry8sa
