language: cpp
compiler: gcc
os:       linux

# Installing additional tools
addons:
  apt:
    packages:
#    - valgrind
#    - python-yaml
    - lcov

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-test-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#  - pip install --user cpp-coveralls

script:
  - mkdir build && cd build && cmake .. && make VERBOSE=1
  - lcov --zerocounters --directory .
  - ./mylib/test/btest01 --log_level=all
  - ./mylib/test/gtest01

after_success:
  # Copying Coveralls data to a separate folder
  - mkdir -p $TRAVIS_BUILD_DIR/coverals
  - find ../../../bin.v2/ -name "*.gcda" -exec cp "{}" $TRAVIS_BUILD_DIR/coverals/ \;
  - find ../../../bin.v2/ -name "*.gcno" -exec cp "{}" $TRAVIS_BUILD_DIR/coverals/ \;

  # use gcov-4.8
  - sudo rm /usr/bin/gcov && sudo cp /usr/bin/gcov-4.8 /usr/bin/gcov
  - gcov -v

  # Preparing Coveralls data by changind data format to a readable one
  - lcov --capture --directory $TRAVIS_BUILD_DIR/coverals --base-directory ./ --output-file $TRAVIS_BUILD_DIR/coverals/coverage.info

  # ... erasing /usr* and 3rdparty folder data
  - lcov --remove $TRAVIS_BUILD_DIR/coverals/coverage.info "/usr*" "*3rdparty*" -o $TRAVIS_BUILD_DIR/coverals/coverage.info

#  - gcov ./mydaemon/test/gtest01.cpp --object-file ./mydaemon/test/CMakeFiles/gtest01.dir/gtest01.cpp.gcno
#  - gcov ./mylib/mymath.cpp --object-file ./mylib/CMakeFiles/MyMath.dir/mymath.cpp.gcno -l
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
#  - coveralls --gcov-options '\-lp' --verbose --dump coveralls.json

  # Sending data to Coveralls
  - cd $TRAVIS_BUILD_DIR
  - gem install coveralls-lcov
  - coveralls-lcov coverals/coverage.info

after_script:
  - pwd
  - ls -alF .
  - ls -alF ./mydaemon
  - ls -alF ./mylib
  - ls -alF ./mylib/test
  - find . -name "*.gcno*"
#  - cat coveralls.json

notifications:
  slack: j0ny:tlJolYCjWs5eI2DmeZFry8sa
